net.qunqun.zhaiqunOA.UI/Controllers/UserInfoController.cs
using net.qunqun.zhaiqunOA.Bll;
using net.qunqun.zhaiqunOA.BllFactory;
using net.qunqun.zhaiqunOA.IBll;
using net.qunqun.zhaiqunOA.Model;
using net.qunqun.zhaiqunOA.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace net.qunqun.zhaiqunOA.UI.Controllers
{
    public class UserInfoController : Controller
    {
        //
        // GET: /UserInfo/
        IUserInfoBll bll = BllFactoryClass.GetUserInfoBll();
       
        public ActionResult Index()
        {
            int recordCount;
            int pageSize = 7;
            int pageIndex = 1;
            IQueryable<UserInfo> model = bll.SelectByRow<int>(pageSize, pageIndex, c => true, c => c.UserId, out recordCount);
            ViewData.Model = model;
            return View();
        }
        public ActionResult Add()
        {
            return View();
        }
       [HttpPost]
        public ActionResult Add(UserInfo model)
        {
            model.SubBy = 1;
            model.SubTime = DateTime.Now;
            model.IsDelete = false;
          
             bool b= bll.Add(model);
             if (b)
             {
                 return Redirect(Url.Action("Index"));
             }
             else
             {
                 return Content("增加数据失败");
             }
        }
    }
}

net.qunqun.zhaiqunOA.UI/Views/UserInfo/Add.cshtml
@model net.qunqun.zhaiqunOA.Model.UserInfo
@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>
<table>
     @Html.BeginForm("Add","UserInfo")
    {
       <tr>
           <td>@Html.LabelFor(c=>c.UserName)</td>
           <td>@Html.TextBoxFor(c=>c.UserName)</td>
       </tr>
     <tr>
           <td>@Html.LabelFor(c=>c.UserPwd)</td>
           <td>@Html.PasswordFor(c=>c.UserPwd)</td>
       </tr>
         <tr>
           <td>@Html.LabelFor(c=>c.UserTrueName)</td>
           <td>@Html.TextBoxFor(c=>c.UserTrueName)</td>
       </tr>
        <tr>
           <td></td>
           <td>
               <input type="submit"  value="增加" />
           </td>
       </tr>
    }
</table>

net.qunqun.zhaiqunOA.UI/Views/UserInfo/Index.cshtml
@model   IQueryable<net.qunqun.zhaiqunOA.Model.UserInfo>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@Html.ActionLink("增加","Add")
<table>
    <thead>
        <tr>
            <th>编号</th> <th>用户名</th> <th>真实姓名</th> 
        </tr>
    </thead>
    <tbody>
          @foreach (var item in ViewData.Model)
          {
              <tr><td>@item.UserId</td><td>@item.UserName</td><td>@item.UserTrueName</td></tr>
          }
    
    </tbody>
</table>