net.qunqun.zhaiqunOA.UI/Controllers/RoleInfoController.cs
using net.qunqun.zhaiqunOA.IBll;
using net.qunqun.zhaiqunOA.Model;
using net.qunqun.zhaiqunOA.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace net.qunqun.zhaiqunOA.UI.Controllers
{
    public class RoleInfoController : Controller
    {
        //
        // GET: /RoleInfo/
        public IRoleInfoBLL roleInfoBll { set; get; }
        public IActionInfoBll actionInfoBll { get; set; }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetPageList(int page, int rows)
        {
            int rowCount;
            var result = roleInfoBll.SelectByRow(rows, page, c => c.IsDelete == false, c => c.RoleId, out rowCount)
                .Select(u => new { u.RoleId, u.RoleName });
            return Json(new { total = rowCount, rows = result });
        }
        public ActionResult Add(RoleInfo model)
        {
            string result = "0";
            model.IsDelete = false;
            model.SubBy = 1;
            model.SubTime = DateTime.Now;
            bool b = roleInfoBll.Add(model);
            if (b)
            {
                result = "1";
            }
            return Content(result);
        }

        public ActionResult Edit(int id)
        {
            RoleInfo model = roleInfoBll.Select(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(RoleInfo model)
        {
            string result = "0";
            model.SubBy = 1;
            model.SubTime = DateTime.Now;
            model.IsDelete = false;
            bool b = roleInfoBll.Edit(model);
            if (b)
            {
                result = "1";
            }
            return Content(result);
        }

        public ActionResult Remove(int id)
        {
            string result = "0";
            bool b = roleInfoBll.Delete(id);
            if (b)
            {
                result = "1";
            }
            return Content(result);
        }
        public ActionResult SetAction(int id)
        {
            RoleSetActionModel ra = new RoleSetActionModel();
            ra.RoleModel = roleInfoBll.Select(id);
            ra.ActionModels = actionInfoBll.Select(u => u.IsDelete == false).ToList();

            return View(ra);
        }
        [HttpPost]
        public ActionResult SetAction(int roleId, string ids)
        {
            string result = "0";
            List<int> list = new List<int>();
            foreach (var id in ids.Split(','))
            {
                list.Add(int.Parse(id));
            }
           bool b= roleInfoBll.SetAction(roleId, list.ToArray());
           if (b)
           {
               result = "1";
           }
            return Content(result);
        }
    }

}

net.qunqun.zhaiqunOA.UI/Views/RoleInfo/Edit.cshtml
@model  net.qunqun.zhaiqunOA.Model.RoleInfo
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <script src="../../Scripts/jquery-1.7.1.min.js"></script>
    <script src="../../Scripts/jquery.easyui.min.js"></script>
    <script src="../../Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <title>Edit</title>
    <script  type="text/javascript">

        function EditAfer(msg) {
            window.parent.EditAfer(msg);
       
        }
        function FormSubmit() {
            $("form").submit();
        }
    </script>
</head>
<body>
    <div>
        @using (Ajax.BeginForm("Edit", "RoleInfo", new AjaxOptions() {

            OnSuccess = "EditAfer"
        }))
        {
            <table>
                <tr>
                    <td>角色名称：</td>
                    <td>
                        @Html.TextBoxFor(d=>d.RoleName)
                        <input type="hidden" name="RoleId" value="@Model.RoleId" />
                        <input type="hidden" name="IsDelete" value="@Model.IsDelete" />
                    </td>
                </tr>
                <tr>
                     <td>说明：</td>
                    <td>@Html.TextBoxFor(d=>d.Remark)</td>
                </tr>
            </table> 
        }
    </div>
</body>
</html>

net.qunqun.zhaiqunOA.UI/Views/RoleInfo/Index.cshtml
@model  net.qunqun.zhaiqunOA.Model.RoleInfo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Index</title>
    <link href="../../Content/MyFile/easyUithemes/icon.css" rel="stylesheet" />
    <link href="../../Content/MyFile/easyUithemes/default/easyui.css" rel="stylesheet" />
    <script src="../../Scripts/jquery-1.7.1.min.js"></script>
    <script src="../../Scripts/jquery.easyui.min.js"></script>
    <script src="../../Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script  type="text/javascript">
    $(function () {
        $("#addDiv").hide();
        $("#editDiv").hide();
        $("#setActionDiv").hide();
        InitData();

    });

    function InitData(query) {
        $("#tt").datagrid({
            url: '@Url.Action("GetPageList","RoleInfo")',
                title: '角色列表',
                width: 700,
                height: 400,
                fitColumns: true,
                idField: 'RoleId',
                loadMsg: '正在加载角色的信息...',
                pagination: true,
                singleSelect: true,
                pageSize: 10,
                pageNumber: 1,
                pageList: [10, 20, 30],
                queryParams: query,
                columns: [[
						{ field: 'ck', checkbox: true, align: 'left', width: 50 },
						{ field: 'RoleId', title: '主键', width: 80 },
						{ field: 'RoleName', title: '用户名', width: 120 },
                ]],
                toolbar: [{
                    id: 'toolbarAdd',
                    text: '添加',
                    iconCls: 'icon-add',
                    handler: function () {
                        AddShow();
                    },
                },
                {
                    id: 'toolbarEdit',
                    text: '修改',
                    iconCls: 'icon-edit',
                    handler: function () {
                        EditShow();
                    }
                },
                 {
                     id: 'toolbarRemove',
                     text: '删除',
                     iconCls: 'icon-Remove',
                     handler: function () {
                         RemoveShow();
                     }
                 },
                 {
                     id: 'toolbarSetAction',
                     text: '设置权限',
                     iconCls: 'icon-Redo',
                     handler: function () {
                         SetActionShow();
                     }
                 }],

            });
        }
        function RemoveShow() {
            var row = $('#tt').datagrid("getSelected");
            if (row == null) {
                $.messager.alert("提示", "请选择您要删除的行");
                return;
            }
            $.messager.confirm("提示", "确定要删除么", function (msg) {
                if (msg) {
                    $.post('@Url.Action("Remove","RoleInfo")', { id: row["RoleId"] }, function (msg) {
                     if (msg == "1") {
                         InitData();
                     }
                     else {
                         $.messager.alert("提示", "删除数据失败，请稍后重试");
                     }
                 });
             }
            });

     }

     function EditShow() {
         var row = $('#tt').datagrid("getSelected");
         if (row == null) {
             $.messager.alert("提示", "修改数据失败");
             return;
         }
         $("#editDiv").show();
         $("#editDiv  iframe").attr("src", '@Url.Action("Edit","RoleInfo")?id=' + row["RoleId"]);
            $("#editDiv").dialog({
                title: "用户",
                collapsible: true,
                minimizable: true,
                maximizable: true,
                resizable: true,

                buttons: [{
                    text: "修改",
                    iconCls: "icon-add",
                    handler: function () {
                        $("#editDiv iframe")[0].contentWindow.FormSubmit();
                    }
                }, {
                    text: "取消",
                    iconCls: "icon-cancel",
                    handler: function () {
                        $("#editDiv").dialog("close");
                    }
                }]
            });
        }
    function EditAfer(msg) {
            if (msg == "1") {
                $("#editDiv").dialog("close");
                InitData();
            }
            else {
                $.messager.alert("提示", "修改失败，请稍后重试");
            }
        }
        function AddShow() {
            $("#addDiv").show();
            $("#addDiv input,textarea").val('');
            $("#addDiv").dialog({
                title: "添加juese",
                collapsible: true,
                minimizable: true,
                maximizable: true,
                resizable: true,

                buttons: [{
                    text: "添加",
                    iconCls: "icon-add",
                    handler: function () {
                        $("#addDiv form").submit();
                    }
                }, {
                    text: "取消",
                    iconCls: "icon-cancel",
                    handler: function () {
                        $("#addDiv").dialog("close");
                    }
                }]
            });
        }
        function AddAfter(msg) {
            if (msg == "1") {
                $("#addDiv").dialog("close");
                InitData();
            }
            else {
                $.messager.alert("提示", "添加失败，请稍后重试");
            }
        }
        function SetActionShow() {
            var row = $('#tt').datagrid("getSelected");
            if (row==null) {
                $.messager.alert("提示", "请选择您要设置的项");
                return;
            }
            $("#setActionDiv").show();
            $("#setActionDiv  iframe").attr("src", '@Url.Action("SetAction","RoleInfo")?id=' + row["RoleId"]);
            $("#setActionDiv").dialog({
                title: "用户",
                collapsible: true,
                minimizable: true,
                maximizable: true,
                resizable: true,
                width: 520,
                height:400,
                buttons: [{
                    text: "设置",
                    iconCls: "icon-redo",
                    handler: function () {
                        $("#setActionDiv iframe")[0].contentWindow.FormSubmit();
                    }
                }, {
                    text: "取消",
                    iconCls: "icon-cancel",
                    handler: function () {
                        $("#setActionDiv").dialog("close");
                    }
                }]
            });
        }
    function SetActionAfter(msg) {
        if (msg == "1") {
            $("#setActionDiv").dialog("close");
            
        }
        else {
            $.messager.alert("提示","设置失败，请稍后再试");
        }
    }
    </script>
</head>
<body>
   
    <!--列表-->
    <div>
        <table id="tt"></table>
    </div>
    <!--添加-->
    <div  id="addDiv">
          @using (Ajax.BeginForm("Add", "RoleInfo", new AjaxOptions() {
               
                OnSuccess="AddAfter"
          }))
          {
              <table>
                  <tr>
                      <td>角色名:</td>
                      <td>@Html.TextBoxFor(c=>c.RoleName)</td>
                  </tr>
                  <tr>
                      <td>备注：</td>
                      <td>@Html.TextBoxFor(c=>c.Remark)</td>
                  </tr>
              </table>
          
          }
    </div>
    <!--修改-->
    <div  id="editDiv">
        <iframe   ></iframe>
    </div>
    <!--权限授予-->

    <div id="setActionDiv">
        <iframe  width="100%"  height="100%"></iframe>
    </div>
</body>
</html>

net.qunqun.zhaiqunOA.UI/Views/RoleInfo/SetAction.cshtml
@model  net.qunqun.zhaiqunOA.UI.Models.RoleSetActionModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>SetAction</title>
    <script src="../../Scripts/jquery-1.7.1.min.js"></script>
    <script  type="text/javascript">
        function FormSubmit() {
            var ids = "";
            $(':checked').each(function () {
                ids += $(this).val() + ",";
            });
            ids = ids.substring(0, ids.length - 1);
            $.post('@Url.Action("SetAction","RoleInfo")', {
                ids: ids,
                roleId: $('#RoleId').val()

            }, function (msg) {
                window.parent.SetActionAfter(msg);
            });
        }
    </script>
</head>
<body>
    <div>
        @{
            var roleinfo = Model.RoleModel;
            var actionModels = Model.ActionModels;
        }
         <input type="hidden"  id="RoleId"  value="@roleinfo.RoleId"/>
        <span>为<font>@roleinfo.RoleName</font>分配权限</span>
        <table>
            <tr>
                @{
                    int count = 0;
                    foreach (var item in actionModels)
                    {
                        count++;
                    <td>
                        <input type="checkbox"  value="@item.ActionId" 
                            @if (roleinfo.ActionInfo.Contains(item))
                            {
                               @Html.Raw("checked");
                            }
                            />@item.ActionTitle
                    </td>
                    if (count % 5 == 0)
                    {
                        @Html.Raw("</tr><tr>");
                    }
                    }
                }
            </tr>
        </table>
    </div>
</body>
</html>